spring:
  application:
    name: coreflow
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/coreflow
    username: coreflow
    password: coreflow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: coreflow-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"# Configuration RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}  # Assurez-vous de définir cette variable d'environnement
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
aws:
  region: eu-west-3
  s3:
    bucket-name: coreflow-invoices
    endpoint: http://localhost:4566 # URL de LocalStack (à remplacer par null/vide en prod AWS)
    access-key: test
    secret-key: test
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose tout les endpoints de management (health, metrics, etc.)
  endpoint:
    health:
      show-details: always                  # Affiche le détail de la santé (état de la BDD, Kafka, RabbitMQ)
    prometheus:
      enabled: true                         # Active le formatage des données pour Prometheus
  metrics:
    tags:
      application: coreflow-service         # Tag utilisé pour identifier ton app dans Grafana
